"""ROS 2 description package generator (targets Jazzy + Gazebo Sim).

Layout produced::

    <robot>_description/
        package.xml            (ament_cmake)
        CMakeLists.txt
        urdf/<robot>.xacro     + materials.xacro + <robot>.ros2control
        meshes/*.stl           (copied from the export dir)
        launch/display.launch.py
        launch/gazebo.launch.py
        rviz/display.rviz
        config/ros_gz_bridge.yaml
"""

from __future__ import annotations

import shutil
from pathlib import Path

from .model import Robot
from .urdf_writer import (
    build_materials_xacro,
    build_ros2_control_xacro,
    build_xacro_main,
)

PACKAGE_XML = """\
<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>{package}</name>
  <version>0.1.0</version>
  <description>URDF description of {robot}, generated by fusion2urdf</description>
  <maintainer email="user@example.com">fusion2urdf</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <exec_depend>robot_state_publisher</exec_depend>
  <exec_depend>joint_state_publisher</exec_depend>
  <exec_depend>joint_state_publisher_gui</exec_depend>
  <exec_depend>rviz2</exec_depend>
  <exec_depend>xacro</exec_depend>
  <exec_depend>ros_gz_sim</exec_depend>
  <exec_depend>ros_gz_bridge</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
"""

CMAKELISTS = """\
cmake_minimum_required(VERSION 3.8)
project({package})

find_package(ament_cmake REQUIRED)

install(
  DIRECTORY urdf meshes launch rviz config
  DESTINATION share/${{PROJECT_NAME}}
)

ament_package()
"""

DISPLAY_LAUNCH = '''\
"""Display {robot} in RViz2 with joint_state_publisher_gui."""

import os

import xacro
from ament_index_python.packages import get_package_share_directory
from launch import LaunchDescription
from launch.actions import DeclareLaunchArgument
from launch.conditions import IfCondition, UnlessCondition
from launch.substitutions import LaunchConfiguration
from launch_ros.actions import Node


def generate_launch_description():
    share_dir = get_package_share_directory("{package}")

    xacro_file = os.path.join(share_dir, "urdf", "{robot}.xacro")
    robot_urdf = xacro.process_file(xacro_file).toxml()

    rviz_config = os.path.join(share_dir, "rviz", "display.rviz")

    gui_arg = DeclareLaunchArgument(name="gui", default_value="True")
    show_gui = LaunchConfiguration("gui")

    return LaunchDescription(
        [
            gui_arg,
            Node(
                package="robot_state_publisher",
                executable="robot_state_publisher",
                parameters=[{{"robot_description": robot_urdf}}],
            ),
            Node(
                condition=UnlessCondition(show_gui),
                package="joint_state_publisher",
                executable="joint_state_publisher",
            ),
            Node(
                condition=IfCondition(show_gui),
                package="joint_state_publisher_gui",
                executable="joint_state_publisher_gui",
            ),
            Node(
                package="rviz2",
                executable="rviz2",
                arguments=["-d", rviz_config],
                output="screen",
            ),
        ]
    )
'''

GAZEBO_LAUNCH = '''\
"""Spawn {robot} in Gazebo Sim (gz-sim, ROS 2 Jazzy)."""

import os

import xacro
from ament_index_python.packages import get_package_share_directory
from launch import LaunchDescription
from launch.actions import IncludeLaunchDescription, TimerAction
from launch.launch_description_sources import PythonLaunchDescriptionSource
from launch_ros.actions import Node


def generate_launch_description():
    pkg_ros_gz_sim = get_package_share_directory("ros_gz_sim")
    share_dir = get_package_share_directory("{package}")

    xacro_file = os.path.join(share_dir, "urdf", "{robot}.xacro")
    robot_description = {{"robot_description": xacro.process_file(xacro_file).toxml()}}
    bridge_config = os.path.join(share_dir, "config", "ros_gz_bridge.yaml")

    gazebo = IncludeLaunchDescription(
        PythonLaunchDescriptionSource(
            os.path.join(pkg_ros_gz_sim, "launch", "gz_sim.launch.py")
        ),
        launch_arguments={{"gz_args": "-r -v 4 empty.sdf"}}.items(),
    )

    robot_state_publisher = Node(
        package="robot_state_publisher",
        executable="robot_state_publisher",
        output="screen",
        parameters=[robot_description],
    )

    # Delayed spawn with renaming disabled to avoid duplicate entities.
    spawn_robot = TimerAction(
        period=5.0,
        actions=[
            Node(
                package="ros_gz_sim",
                executable="create",
                arguments=[
                    "-topic", "/robot_description",
                    "-name", "{robot}",
                    "-allow_renaming", "false",
                    "-z", "0.1",
                ],
                output="screen",
            )
        ],
    )

    ros_gz_bridge = Node(
        package="ros_gz_bridge",
        executable="parameter_bridge",
        parameters=[{{"config_file": bridge_config}}],
        output="screen",
    )

    return LaunchDescription(
        [gazebo, robot_state_publisher, spawn_robot, ros_gz_bridge]
    )
'''

RVIZ_CONFIG = """\
Panels:
  - Class: rviz_common/Displays
    Name: Displays
Visualization Manager:
  Displays:
    - Class: rviz_default_plugins/Grid
      Enabled: true
      Name: Grid
    - Class: rviz_default_plugins/RobotModel
      Description Topic:
        Value: /robot_description
      Enabled: true
      Name: RobotModel
    - Class: rviz_default_plugins/TF
      Enabled: true
      Name: TF
  Global Options:
    Fixed Frame: base_link
    Frame Rate: 30
  Tools:
    - Class: rviz_default_plugins/MoveCamera
  Views:
    Current:
      Class: rviz_default_plugins/Orbit
      Distance: 1.5
      Name: Current View
"""

BRIDGE_CONFIG = """\
# ros_gz_bridge configuration
- ros_topic_name: /joint_states
  gz_topic_name: /joint_states
  ros_type_name: sensor_msgs/msg/JointState
  gz_type_name: gz.msgs.Model
  direction: GZ_TO_ROS
- ros_topic_name: /clock
  gz_topic_name: /clock
  ros_type_name: rosgraph_msgs/msg/Clock
  gz_type_name: gz.msgs.Clock
  direction: GZ_TO_ROS
"""


def generate_ros2_package(
    robot: Robot,
    output_dir: str | Path,
    meshes_dir: str | Path | None = None,
    package_name: str | None = None,
) -> Path:
    """Write a complete ROS 2 description package. Returns the package path."""
    robot.validate()
    package = package_name or f"{robot.name}_description"
    pkg_dir = Path(output_dir) / package

    for sub in ("urdf", "meshes", "launch", "rviz", "config"):
        (pkg_dir / sub).mkdir(parents=True, exist_ok=True)

    fmt = {"package": package, "robot": robot.name}
    (pkg_dir / "package.xml").write_text(PACKAGE_XML.format(**fmt), encoding="utf-8")
    (pkg_dir / "CMakeLists.txt").write_text(CMAKELISTS.format(**fmt), encoding="utf-8")

    (pkg_dir / "urdf" / f"{robot.name}.xacro").write_text(
        build_xacro_main(robot, package), encoding="utf-8"
    )
    (pkg_dir / "urdf" / "materials.xacro").write_text(
        build_materials_xacro(robot), encoding="utf-8"
    )
    (pkg_dir / "urdf" / f"{robot.name}.ros2control.xacro").write_text(
        build_ros2_control_xacro(robot), encoding="utf-8"
    )

    (pkg_dir / "launch" / "display.launch.py").write_text(
        DISPLAY_LAUNCH.format(**fmt), encoding="utf-8"
    )
    (pkg_dir / "launch" / "gazebo.launch.py").write_text(
        GAZEBO_LAUNCH.format(**fmt), encoding="utf-8"
    )
    (pkg_dir / "rviz" / "display.rviz").write_text(RVIZ_CONFIG, encoding="utf-8")
    (pkg_dir / "config" / "ros_gz_bridge.yaml").write_text(
        BRIDGE_CONFIG, encoding="utf-8"
    )

    if meshes_dir:
        meshes_dir = Path(meshes_dir)
        for link in robot.links:
            if not link.mesh:
                continue
            src = meshes_dir / link.mesh
            if src.exists():
                shutil.copy2(src, pkg_dir / "meshes" / src.name)

    return pkg_dir
